### ISSUE TITLE
Translation / i18n support

### ISSUE THREAD

**Issue by guyguy333** [ory/elements#105]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently, text can't be translated. It's hardcoded in React components.

### Describe your ideal solution

Add support for i18n / translation so we can translate / change any text in components.

### Workarounds or alternatives

None

### Version

latest

**Comment by Benehiko** [comment]
In progress here https://github.com/ory/elements/pull/130

**Comment by Benehiko** [comment]
This has now been added to the latest version
