### ISSUE TITLE
Toggle switch to show the user's password when on the UserSettingsCard

### ISSUE THREAD

**Issue by kevinbtesar** [ory/elements#116]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

My feature request is not related to a problem or issue. This request concerns the SettingsFlow. The concern is that once the user has submitted the password reset code, we take them to the UserSetting card within the auth flow. At this point, they can enter their new password. However, there is no way to confirm they have entered their desired value. If an incorrect value is entered, they are forced to go through the password reset process for a second time.

### Describe your ideal solution

Our ideal solution is a toggle switch that shows the entered value in the password field as clear text.  I'll paste in a mockup our Project Manager and Lead Designer created in Zeplin that illustrates our request.

![image](https://github.com/ory/elements/assets/54149309/2e152ecf-7976-4b3e-9ba2-1b1353d8279f)

### Workarounds or alternatives

An alternative would be a password confirmation box. I.e., a second password input field that confirms the characters match the value in the first password input field.

### Version

v0.0.1-beta.7

### Additional Context

I have no additional context at this time.

Thank you

**Comment by Benehiko** [comment]
I have been looking into this, please take a look at the draft PR. Suggestions are welcome! :)

**Comment by Benehiko** [comment]
Hi @kevinbtesar 

I actually found another problem with this implementation when using native form posts (since there are now technically two fields with the same name in the form). I'm busy fixing that quick in a different PR.

**Comment by kevinbtesar** [comment]
@Benehiko That sounds like a plan. No rush. However, I will keep on an eye on this thread to inform my bosses of your progress.

Should the issue be reopened until you get back to it?

**Comment by Benehiko** [comment]
Sorry about all of the delays, the latest version should now be working :)

**Comment by kevinbtesar** [comment]
@Benehiko No worries at all! 
While I can't test it out yet, I looked at your changes, and it seems to be super easy to implement. Many thanks from me, my team, and everyone at Pusar!!
