### ISSUE TITLE
Unable to start Storybook

### ISSUE THREAD

**Issue by aeneasr** [ory/elements#13]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I get an error when running Storybook on a fresh install

### Reproducing the bug

1. Clone repo
2. `npm i`
3. `npm run storybook`

Results in:

<img width="2672" alt="Bildschirmfoto 2022-10-05 um 17 08 06" src="https://user-images.githubusercontent.com/3372410/194095457-90dd7a5f-e48a-4e30-a880-22708f0ad706.png">

### Relevant log output

```shell
ℹ ｢wdm｣: Compiled successfully.
╭──────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                          │
│   Storybook 6.5.10 for React started                                                     │
│   5.86 s for manager and 2.45 s for preview                                              │
│                                                                                          │
│    Local:            http://localhost:6006/                                              │
│    On your network:  http://192.168.2.183:6006/                                          │
│                                                                                          │
│   A new version (6.5.12) is available!                                                   │
│                                                                                          │
│   Upgrade now: npx storybook@latest upgrade                                              │
│                                                                                          │
│   Read full changelog: https://github.com/storybookjs/storybook/blob/next/CHANGELOG.md   │
│                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────╯
5:06:08 PM [vite] ✨ new dependencies optimized: @storybook/react/dist/esm/client/docs/config, @storybook/react/dist/esm/client/preview/config, @storybook/addon-links/preview.js, @storybook/addon-docs/preview.js, @storybook/addon-actions/preview.js, ...and 4 more
5:06:08 PM [vite] ✨ optimized dependencies changed. reloading
5:06:09 PM [vite] Internal server error: Failed to resolve entry for package "@ory/elements". The package may have incorrect main/module/exports specified in its package.json.
  Plugin: vite:import-analysis
  File: /Users/foobar/workspace/js/elements/.storybook/preview.tsx
      at packageEntryFailure (file:///Users/foobar/workspace/js/elements/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:34705:11)
      at resolvePackageEntry (file:///Users/foobar/workspace/js/elements/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:34702:5)
      at tryNodeResolve (file:///Users/foobar/workspace/js/elements/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:34452:20)
      at Context.resolveId (file:///Users/foobar/workspace/js/elements/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:34254:28)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.resolveId (file:///Users/foobar/workspace/js/elements/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35511:32)
      at async TransformContext.resolve (file:///Users/foobar/workspace/js/elements/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35276:23)
      at async normalizeUrl (file:///Users/foobar/workspace/js/elements/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40249:34)
      at async TransformContext.transform (file:///Users/foobar/workspace/js/elements/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:40389:47)
```

### Version

master

```
% node --version
v16.15.1
```

**Comment by Benehiko** [comment]
Steps to run the storybook:

1. npm i
2. npm run initialize
3. npm run build or npm run build:clean
4. npm run storybook

After step 2 and 3 has been run initially, storybook should hot reload on changes made to the react components. 
To break it down, `initialize` does a lerna specific way of dependency management  using https://github.com/lerna/lerna/tree/main/commands/bootstrap. We run `npm i` in step 1 to install lerna and some other smaller tools - we might need to clean it up so it doesn't unnecessarily install everything in every workspace. When running `npm run build` lerna takes care of the dependencies and build order, use this command as a first run. If you want to ignore any caching done by lerna use `npm run build:clean`. To build a specific package you can run `npm run build:<package>` e.g. `build:react`.
