### ISSUE TITLE
Ory Account Experience - Login - Show/hide password button toggled via tabbing

### ISSUE THREAD

**Issue by BrandonNoad** [ory/elements#155]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/network/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/network/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Ory Network Project

https://account.toolsfortana.com

### Describe the bug

 Input your password, tab to the "Sign in" button, and when you tab over the show/hide eye icon, it triggers a click on it, revealing your password.

![password_revealed](https://github.com/ory/network/assets/1979809/e6adab93-a4f9-4ba7-a134-2d0f07f9bd22)

### Reproducing the bug

See description. 

Bug can be reproduced here: https://account.toolsfortana.com/ui/login

### Version

Ory Network

### On which operating system are you observing this issue?

Ory Network

### In which environment are you deploying?

Ory Network

**Comment by Benehiko** [comment]
Thank you for the report! I'll take a look as soon as I have time

**Comment by Benehiko** [comment]
I'll update the Account Experience soon with this release https://github.com/ory/elements/releases/tag/v0.1.0-beta.11 and it should then be fixed.
