### ISSUE TITLE
Add support for prompt=select_account during settings OIDC link

### ISSUE THREAD

**Issue by jonas-jonas** [ory/elements#268]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://www.ory.sh/l/sign-up-newsletter).

### Describe your problem

When linking OIDC account, it is common that users have multiple Google accounts signed in at once. Depending on what they chose before, Google might choose to skip account selection and consent, making it very difficult to choose the right account to link during settings OIDC linking. 

### Describe your ideal solution

Kratos already supports `upstream_parameters`, and thus `prompt`, and we should just force the [select_account](https://developers.google.com/identity/openid-connect/openid-connect#authenticationuriparameters) prompt for Google (and possibly others, though it's not clear, what the side effects of this are

### Workarounds or alternatives

-

### Version

master

**Comment by jonas-jonas** [comment]
Fixed via https://github.com/ory/elements/pull/266

**Comment by aeneasr** [comment]
Shouldn't this be solved in kratos instead? Otherwise it only works for elements but not native and other sdks

**Comment by aeneasr** [comment]
Generally I think flow logic shouldn't belong in Ory Elements, otherwise it will be quite challenging to have consistent use experiences across different sdks (versions and clients).

**Comment by jonas-jonas** [comment]
Yea I was thinking that we could add an option to the Oidc provider config to configure these parameters by default. I think that would make most sense. I'll work on that.

**Comment by aeneasr** [comment]
That might be already possible. I'm also OK to show account selection for account linking only. If you always pass account_select it will cause issues when double redirecting, see: https://github.com/ory/kratos/pull/4064
