### ISSUE TITLE
feat: fields should automatically trim whitespaces around values (e.g. OTP)

### ISSUE THREAD

**Issue by jonasbadstuebner** [ory/elements#60]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

When I double clicked and `CTRL+C`-ed the OTP from my mail, it copied a whitespace in front of it and I didn't notice, only after the form told me, the OTP was wrong.

### Describe your ideal solution

Maybe there is an easy way to trim the value of some fields, where it makes sense. This is minor priority, but very convenient. :)

### Workarounds or alternatives

Don't know if there are any workarounds right now - probably only implementing this whole library on your own?

### Version

v0.0.1-alpha.27

**Comment by jonas-jonas** [comment]
Oh, great idea! We could actually do this in Kratos itself, so that this would apply to other implementations as well. @aeneasr WDYT?

**Comment by aeneasr** [comment]
I don't think the whitespaces are coming from Kratos, so fixing this in Ory Elements is a good idea :)

**Comment by DrBu7cher** [comment]
They are not coming from kratos, but if kratos would ignore/trim them, the frontend/selfservice would not have to handle that.
Still I think it would be best to implement it in ory elements. :)

**Comment by misamu** [comment]
Fixing this issue in Ory Elements would require JS to trim the data, so not that good.

I think that the best would be for Kratos self-service to return an input field that contains `InputAttribute.Pattern` with valid characters that I think in this case would be `[a-zA-Z0-9]+`.

A change to CSS would be a good to show error border when pattern does not match. Currently that is shown only when there is no focus to the field.

This would be nice also in other places for example recovery code input.
