### ISSUE TITLE
Flow error handler

### ISSUE THREAD

**Issue by jgillich** [ory/elements#62]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

One of the most difficult aspects of integrating Ory into my frontend has been the flow error handling. I'm currently using this in my Next.js project, based on kratos-selfservice-ui-react-nextjs : https://gist.github.com/jgillich/b078cb3de9047054a458049187f27bbd

It has grown over time, and I'm pretty sure there are subtle bugs there because Sentry picks up on them occasionally, but I'm not sure how to resolve them. Porting it to the latest version of the ory client has been difficult as well. There are some error types in the client, but it doesn't seem complete nor do I know how to detect which error I actually have

This repo once again contains a bunch of boilerplate for error handling, and it also doesn't appear to handle everything correctly (#53)

I was excited about Ory Elements until I realized it doesn't (yet) solve this major pain point.

### Describe your ideal solution

Ory should provide an easy to use method that takes an error type and returns actionable results, something like:

```typescript
interface ParsedFlowError {
  type: "redirect_to" | "bad_request" | "server_error"
  redirect_url?: string
  error_message?: string
}
```

This would be entirely framework-agnostic.

### Workarounds or alternatives

Try to do it yourself, poorly

### Version

latest

**Comment by aeneasr** [comment]
Absolutely, this problem has been on the back of our heads for some while now. We also generally want to fix this for mobile UIs. But we don't have a good concept yet :(
