### ISSUE TITLE
Add support to tick 'privacy policy/terms read' with link

### ISSUE THREAD

**Issue by DrBu7cher** [ory/elements#65]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

If you have a user registering on your site you want to make sure they read and understood the terms and read the privacy policy. So I am missing a way to specify a link to either of them and have the elements create a checkbox with some text? :)
Maybe I have to build my own UI then, but I like the seamless integration with Ory Elements and the components, so I would prefer a "native" solution.
It can also be a legal issue.

### Describe your ideal solution

Props to specify the link for `privacy policy` and `terms and conditions`.
```js
additionalProps: {
  privacyPolicyURL: "privacy",
  termsURL: "terms.pdf",
},
```

### Workarounds or alternatives

Building my own UI...

### Version

v0.0.1-alpha.27

### Additional Context

Is it possible to save that information in Ory then? Can I create a schema for kratos that holds the "y" for "readPrivacyPolicy" or something? It is for legal reasons.

**Comment by Benehiko** [comment]
Hi @DrBu7cher 

I think we could probably add an additional field to the props for the checkbox to accommodate this https://github.com/ory/elements/blob/97130656b4c3ec00fec6224f9c266a538641abb5/src/react-components/ory/helpers/node.tsx#L181-L195

But this is also quite nested... Maybe a better solution would be to detect URLs inside the label and have it wrapped by a link?

You can then specify the link inside the Ory Schema when adding the Terms of Service and Privacy Policy checkbox items?

**Comment by DrBu7cher** [comment]
My question aims at the UserAuthCard - can I add my own Checkbox here? Then this issue can be closed, because it can be worked around easily.

**Comment by DrBu7cher** [comment]
Or how can I add my own „generic stuff“ between the last field and the button anyway?

**Comment by DrBu7cher** [comment]
Should the `children` field be for that? It is not documented and I couldn’t find, where it is used/consumed.
https://github.com/ory/elements/blob/66164725ebb08ea661da57a2cf9aeb5d986d3ba3/src/react-components/ory/user-auth-card.tsx#L69

**Comment by Benehiko** [comment]
No, you cannot adjust the Checkbox currently through the `UserAuthCard` props. Due to the reasons given above. 

We can maybe expose a way to override the elements used within `UserAuthCard` or props for specific things like labels. 

It is a bit tricky though since the elements get mapped dynamically based on data provided by Ory Kratos. So overriding a Checkbox for example will override all Checkboxes being mapped by Ory Kratos. That's why this problem requires a bit of thought. 

/cc @mszekiel

**Comment by DrBu7cher** [comment]
Just for me, since this might give me a way to work around this issue (without a link in the checkbox-label): How can I set up Kratos to show checkboxes in the UserAuthCard then?
BR

**Comment by Benehiko** [comment]
You can add a boolean trait to your Identity Schema which will tell Ory Elements to render the checkbox for you.

```json5
{
...
"properties": {
    "newsletter": {
    "type": "boolean",
    "title": "Newsletter subscription"
}
...
```

https://www.ory.sh/docs/kratos/manage-identities/identity-schema#example-with-name-and-newsletter-opt-in

**Comment by DrBu7cher** [comment]
Thank you very much!

**Comment by DrBu7cher** [comment]
> No, you cannot adjust the Checkbox currently through the `UserAuthCard` props. Due to the reasons given above.
> 
> We can maybe expose a way to override the elements used within `UserAuthCard` or props for specific things like labels.
> 
> It is a bit tricky though since the elements get mapped dynamically based on data provided by Ory Kratos. So overriding a Checkbox for example will override all Checkboxes being mapped by Ory Elements based on data given by Ory Kratos. That's why this problem requires a bit of thought.
> 
> /cc @mszekiel

What is the `children` field for then?

And I think overriding could happen based on trait/field name? It would maybe even enable localization? Also, how do I specify the label for the password field? The other labels I can change by editing the kratos schema, but what about password label?

**Comment by Benehiko** [comment]
> What is the children field for then?

Currently nothing. The intent was to have the form customization through children, but the plan was changed while this was being implemented - so it's just code that wasn't deleted...

You are correct that you can do overriding with trait/field names using the identity schema, but it will only do this partially and not everything afaik is used from the schema e.g. "Sign in with GitHub" is a string constructed within Kratos. There is a discussion about localization here  
https://github.com/ory/elements/issues/64
