### ISSUE TITLE
Recovery flow broken

### ISSUE THREAD

**Issue by hyperknot** [ory/elements#79]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

On the Recovery flow, once you enter the code, it breaks the app. 

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/494223/213556179-5ce153af-5760-4d50-a1fa-1c8f0651c3b9.png">

The reason is that it receives a 422 about a redirect which is not handled.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/494223/213596103-6c02add3-d5c4-4609-90e5-bb63c910d875.png">

Bug 2:
After this, if the user clicks the Submit again, the app goes in an infinite redirect/reload bug. It's quite hard to stop it, easiest way is to close the browser tab altogether.

### Reproducing the bug

Run official Next.js example.
Try to complete the Recovery flow, enter Code.

### Version

master

I'm using Ory Network + ory tunnel as in the official example.

**Comment by meotimdihia** [comment]
I got this problem too.

**Comment by misamu** [comment]
This has been fixed with the latest merged code.

**Comment by Benehiko** [comment]
This should be fixed and is now tested https://github.com/ory/elements/blob/main/examples/nextjs-spa/e2e/recovery.spec.ts
