### ISSUE TITLE
Infinite reload loops

### ISSUE THREAD

**Issue by hyperknot** [ory/elements#80]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

The default part in HandleError can cause infinite reload loops.

https://github.com/ory/elements/blob/6e1184ee0a3bb90d4aa25f0e8170fbe7248e9780/examples/nextjs-spa/pkg/hooks.tsx#L72-L75

I recommend changing it to the one before, where we only reload the path.

### Reproducing the bug

Next.js example, go to recovery flow, manually delete the csrf cookie, reload.

### Version

master

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

**Comment by meotimdihia** [comment]
I got this problem too.

**Comment by misamu** [comment]
This has been fixed with the latest merged code.
