### ISSUE TITLE
ory-elements loads a 2.4 MB CSS file, does critical CSS overrides

### ISSUE THREAD

**Issue by hyperknot** [ory/elements#81]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Using ory-elements loads a 2.4 MB CSS file (minified size).

This file includes:
- the full Font Awesome icon collection
- the Inter font in 3 font weights
- the JetBrainsMono font in 2 font weights

Most importantly, it also includes normalize.css which is a full CSS reset, basically conflicting with every single project which doesn't use the exact same file.

It also does global style overrides like `textRendering: "geometricPrecision"` etc.

I'm sorry to say but this way it's not usable in any project. This might work on a separate subdomain hosted auth screens, but then the whole point of this project is to do it inside an app, isn't it?

### Reproducing the bug

Build a project, look at the bundled 2.4 MB CSS file.

**Comment by aeneasr** [comment]
Thank you, you’re absolutely right. We will reduce the amount of data we load here and also do away with excessive font loading :)

**Comment by aeneasr** [comment]
@jfcurran maybe we can reduce the number of fonts we load?

**Comment by hyperknot** [comment]
The more critical problem is the global scoped CSS styles and the reset. It can totally break an existing website's CSS if those are loaded.

**Comment by aeneasr** [comment]
Got it, we’ll sort that first. Our UI team is busy shipping our new website this team but we’ll get to this right after. @kmherrmann

**Comment by kmherrmann** [comment]
@Benehiko for visibility

Thanks for the report, @hyperknot . This is definitely not an acceptable size for CSS and we'll work to clean it up!

**Comment by hyperknot** [comment]
The interesting thing is that I've removed everything (fonts, icons, CSS) and nothing broke. Only the font family had to be [commented out](https://github.com/ory/elements/commit/2361c757863faf76a2b9ce5c16d306ceaada0697) as it was hardcoded.

I don't know what's the tiny icon which was used from FontAwesome but I haven't even seen it.

**Comment by Benehiko** [comment]
Hey @hyperknot 

Sorry about this, we will address it soon!

**Comment by Benehiko** [comment]
This should now be resolved with the latest release ([v0.0.1-beta.1](https://github.com/ory/elements/releases/tag/v0.0.1-beta.1))

**Comment by hyperknot** [comment]
Thanks a lot for fixing this! There is still 3 hard-coded font-families.

```
  font-family: "Font Awesome 6 Free";
  font-family: Inter;
  font-family: JetBrainsMono;
```

For Inter I think you might have forgotten one line. 

For JetBrainsMono I guess you might need to introduce a var like `--ory-theme-font-family-mono`.

For the Font Awesome, normally for React there is an [official React package](https://fontawesome.com/v5/docs/web/use-with/react). But it's quite a complicated setup, with some special case for Next.js. If it was me I'd inline the SVG icon and remove the FA fonts and packages.

I think this is the [whole icon](https://fontawesome.com/icons/check?s=solid&f=classic):

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M470.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L192 338.7 425.4 105.4c12.5-12.5 32.8-12.5 45.3 0z"/></svg>
```

**Comment by Benehiko** [comment]
> Thanks a lot for fixing this! There are still 3 hard-coded font-families.
> 
> ```
>   font-family: "Font Awesome 6 Free";
>   font-family: Inter;
>   font-family: JetBrainsMono;
> ```
> 
> For Inter I think you might have forgotten one line.
> 
> For JetBrainsMono I guess you might need to introduce a var like `--ory-theme-font-family-mono`.
> 
> For the Font Awesome, normally for React there is an [official React package](https://fontawesome.com/v5/docs/web/use-with/react). But it's quite a complicated setup, with some special case for Next.js. If it was me I'd inline the SVG icon and remove the FA fonts and packages.
> 
> I think this is the [whole icon](https://fontawesome.com/icons/check?s=solid&f=classic):
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
> 
> <path d="M470.6 105.4c12.5 12.5 12.5 32.8 0 45.3l-256 256c-12.5 12.5-32.8 12.5-45.3 0l-128-128c-12.5-12.5-12.5-32.8 0-45.3s32.8-12.5 45.3 0L192 338.7 425.4 105.4c12.5-12.5 32.8-12.5 45.3 0z"/>
> </svg>
> ```

Thank you for finding these, @mszekiel and I discussed reducing the total css this week. We will be tackling that soon, which would mean removing a lot of font awesome, but this will be handled in a new PR :)

I'll create a new issue to track the css changes :)

**Comment by Mulac** [comment]
Hi there, these fonts are causing problems for us using ory/elements overriding our styles, what's the update on this - I couldn't find the new issue?
