### ISSUE TITLE
Reduce total CSS used in Ory Elements

### ISSUE THREAD

**Issue by Benehiko** [ory/elements#86]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/elements/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/elements/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Ory Elements have a lot of CSS required to work out of the box. 
The list is:
 - Font Awesome (brands)
 - Inter fonts

### Describe your ideal solution

We could reduce the total CSS required by stripping the files from unnecessary icons and fonts which we do not use. 

### Workarounds or alternatives

None.

### Version

v0.0.1-beta.1

**Comment by hyperknot** [comment]
I recommend removing Font Awesome altogether and just inlining that one SVG icon into JSX.
Icon source:
https://github.com/FortAwesome/Font-Awesome/blob/6.x/svgs/solid/check.svg

And to inline in JSX for example:
https://react-svgr.com/playground
